MISRA Compliance Update
aws/Fleet-Provisioning-for-AWS-IoT-embedded-sdk pull request #26
Opened 2022-08-24 22:39 UTC by Skptak

Updated the MISRA.md file to be consistent with the new format. Added DNDEBUG and a DISABLE_LOGGING define for when doing a static analysis build

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2022-08-29 18:43 UTC, jasonpcarroll requested changes

2022-08-29 18:43 UTC, jasonpcarroll commented on MISRA.md
> +The Device Defender Client Library files conform to the [MISRA C:2012](https://www.misra.org.uk)
```suggestion
The Fleet Provisioning Library files conform to the [MISRA C:2012](https://www.misra.org.uk)
```

2022-08-29 18:43 UTC, jasonpcarroll commented on MISRA.md
> -| Deviation | Category | Justification |
no deviations here but deviations in config?

2022-08-30 17:49 UTC, jasonpcarroll approved these changes

2022-08-30 18:53 UTC, AniruddhaKanhere commented on test/include/fleet_provisioning_config.h
> +#ifdef DISABLE_LOGGING
Why is this needed if we are using NDEBUG?

2022-08-30 18:54 UTC, AniruddhaKanhere approved these changes

2022-08-30 19:57 UTC, merged